name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node downgrade
      run: npm i -g n@12.18.0
    - name: Use downgrade
      run: sudo n 12.18.0
    - name: Install Modules
      run: npm i
    - name: Install Node upgrade
      run: npm i -g n@18.12.1
    - name: Use upgrade
      run: sudo n 18.12.1
    - name: Run Build
      run: npm run build
    - name: Run Tests
      run: npm t
